### PR TITLE
Feature/remodel powerunit dowload

### PR DESCRIPTION
**Pull request by ghost**
work in progress, remodel wind download

### CODE REVIEW

**Comment by ghost** [comment]
@Bachibouzouk  finished the task for which I opened this branch ;) there are now merge conflicts in utils.py with the next generation naming process ... Can you solve this? Thanks!

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk finished the task for which I opened this branch ;) there are now merge conflicts in utils.py with the next generation naming process ... Can you solve this? Thanks!

Will do :)

**Comment by Bachibouzouk** [comment]
@solar-c - could you describe briefly what was done in these commits in the CHANGELOG?

**Comment by ghost** [comment]
can this be merged now @Bachibouzouk  @Ludee  ?

**Comment by Bachibouzouk** [comment]
> can this be merged now @Bachibouzouk @Ludee ?

Please see [here](https://github.com/OpenEnergyPlatform/open-MaStR/issues/48#issuecomment-559131692) before :)

**Comment by Bachibouzouk** [comment]
Should the ultimate test before merging that @Ludee  can simply run the code without problem ?

**Comment by Ludee** [comment]
Yes, I want to run the download today! Major run is planned for tonight!

**Review by Bachibouzouk — APPROVED** [review]

**Pull request merged**
