### PR TITLE
add OPSD comparison notebook

### PR DESCRIPTION
**Pull request by BenPortner**
Added another postprocessing notebook. 

Contents:
- statistical comparison of OEP MaStR data to OPSD datasets: 
  - How many entries does each dataset contain? 
  - How many common entries are there?
- during comparison of the datasets I found some wrong EEG IDs. See also issue #12.

### CODE REVIEW

**Comment by BenPortner** [comment]
Any news here?

**Comment by Bachibouzouk** [comment]
> Any news here?

@BenPortner - news concerning which question? If your PR is ready for review, you can tag someone to review it :)

**Comment by BenPortner** [comment]
Still cannot assign reviewers, unfortunately. @Bachibouzouk can you review please?

**Comment by Bachibouzouk** [comment]
> Still cannot assign reviewers, unfortunately. @Bachibouzouk can you review please?

I will do it either today or tomorrow :)

**Comment by Bachibouzouk** [comment]
@BenPortner : could you send me the data you use in this tutorials ? You can find my email address on [this page](https://reiner-lemoine-institut.de/ueber-uns/team/) (I have almost the same picture for my profile)

**Comment by Bachibouzouk** [comment]
@BenPortner - because the new file is large, I will proceed to a merge (as it is an addon which does not interact with other parts, this is ok). Then, once I have the data from you I will make create a PR where I highlight comments and proposed changes. That way we can have the discussion on git.

**Review by Bachibouzouk — APPROVED** [review]

**Comment by BenPortner** [comment]
@Bachibouzouk - Thanks for the merge! 
You can find all data in my fork of the repo:
https://github.com/BenPortner/open-MaStR/tree/feature_postprocessing/postprocessing/data

**Pull request merged**
