### PR TITLE
Release 0.11.0

### LINKED ISSUE #237: Release process for v0.11.1
Since there are some issues concerning the release let's coordinate the last steps.
I found three open issues for [version 0.11.0](https://github.com/OpenEnergyPlatform/open-MaStR/projects/1)

- [x] Create a PR `master` <- `release` 
- [x] Draft an GitHub release 
- [x] Test and approve PR @chrwm @FlorianK13 @deniztepe 
- [x] Publish release on GitHub 
- [x] Make release on PyPI -> https://pypi.org/project/open-mastr/

### PR DESCRIPTION
**Pull request by Ludee**
Make a release on master branch.
Closes #237

### CODE REVIEW

**Review by FlorianK13 — APPROVED** [review]
Too many changes to review. I have tested the new functionalities and the documentation page and it seems to be allright.

**Comment by FlorianK13** [comment]
Maybe @deniztepe can also run some final checks on friday to test the software, so that we can merge it on monday?

**Comment by deniztepe** [comment]
Yes, i could do that

**Review by deniztepe — APPROVED** [review]
I have only corrected a small warning. Other than that the complete download process runs successful on my computer.

**Review by chrwm — APPROVED** [review]

**Pull request merged**
