### PR TITLE
Feature/remodel powerunit dowload

### LINKED ISSUE #31: get_power_unit() and get_all_units() are the same function
**get_power_unit()**
https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/mastr_power_unit_download.py#L41-L68

**get_all_units()**
https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/mastr_power_unit_download.py#L71-L89

Only difference is the parameter [_einheitBetriebsstatus_](https://github.com/OpenEnergyPlatform/open-MaStR/blob/master/import-api/mastr_power_unit_download.py#L56).

### LINKED ISSUE #36: simplify file name methods
The filenames ([csv_name](https://github.com/OpenEnergyPlatform/open-MaStR/blob/dev/import-api/utils.py#L29-L60)) is overingeneered.
Set the filesnames for each technology once and import when needed.

The filenames including the data version is needed to ensure data integrity!

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Closes #31 
Closes #36

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@solar-c - are #41 and #42 the same?
(it is good practice to create a PR, in draft mode if it is work-in-progress, to explicitly give me the information on which branch you are making progress so that I don't need to figure it out myself in the morning ;))

**Comment by Bachibouzouk** [comment]
@solar-c - I pushed new commit (c4edfcbc7f508e59475834e235046ca249797c54) to give you a template idea of how I would like the functions to download units to be formatted

**Comment by ghost** [comment]
in issue #36 @Ludee wants a return to a simple naming method with importing filenames as variables. This is solved here. Data Integrity is guaranteed by a consistent data_version prefix for all potential files in this download run. The data_version is a single variable which can be modified in utils.py @Ludee @Bachibouzouk - maybe you two could discuss the pros/cons of an optional user controlled naming feature and finally decide how to proceed in the future.

**Comment by ghost** [comment]
@Bachibouzouk  this is work in progress, the branch which closes issues #36 and #31 is feature/updates . I used the branch feature/updates as basis to create the new branch feature/remodel_powerunit_download .

**Pull request closed without merging**
