### PR TITLE
Bugfix 367 postgres missing column handling

### PR DESCRIPTION
**Pull request by FlorianK13**

### CODE REVIEW

**Comment by deniztepe** [comment]
I am testing it currently with a new download. It seems like the new columns could be arranged in orm.py . API and xml column names are slightly different. For instance:

```
Hoechstbemessungsleistung = Column(Float)
BiogasHoechstbemessungsleistung = Column(Float)
```

**Comment by deniztepe** [comment]
Does the failing test mean there are new columns again?

`TypeError: 'eegAusschreibungZuschlag' is an invalid keyword argument for StorageEeg`

**Comment by FlorianK13** [comment]
No, I deleted that column because it was not in the documentation. But it comes from the API download apparently, so we need to reintroduce it.

**Review by deniztepe — APPROVED** [review]

**Comment by chrwm** [comment]
Does this mean there were new columns added to the XML? Or API? - in addtion to https://github.com/OpenEnergyPlatform/open-MaStR/issues/351? 
I don't understand the bug from the issue.

**Comment by deniztepe** [comment]
New columns were added to XML, which were undergoing because of automatic column adding as error handling. This handling was not working with local postgres databases apparently.

**Pull request merged**
