### PR TITLE
Implement current wsdl changes

### LINKED ISSUE #349: Print sqlite database path
As a feedback from one user: After the database was downloaded, we should print the database path so that the user can easily find it. Maybe we can work on that in #344 as it belongs to the documentation.

### LINKED ISSUE #351: Review specific WSDL_Patchnote_V1.2.87 changes
Review the [WSDL_Patchnote_V1.2.87](https://test.marktstammdatenregister.de/MaStRHilfe/files/webdienst/WSDL_Patchnotes_V1.2.87.xlsx) related to the "Release-Webdienst" release from 1 October 2022.
The issues collects and implements specific changes, while  #348 remains general discussion.

Relevant changes from patchnote: 
| | | 
| --- | --- |
GetAnlageEegBiomasse.BiogasHoechstbemessungsleistung -> Hoechstbemessungsleistung | umbenannt |
GetEinheitWind.Buergerenergie | hinzugefügt |
GetEinheitSolar.Buergerenergie | hinzugefügt |
GetAnlageEegSpeicher.AnlagenschluesselEeg | hinzugefügt |
GetAnlageEegSpeicher.eegZuschlagsnummer | hinzugefügt |
GetAnlageEegSpeicher.eegAusschreibungZuschlag | hinzugefügt |
GetEinheitWind.Nachtkennzeichen | hinzugefügt |

- [x] Implement wsdl updates
- [x] Update [mastr_datapackage.json](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/open_mastr/soap_api/metadata/mastr_datapackage.json)
- [x] Update documentation on how to update orm and reference this issue

### PR DESCRIPTION
**Pull request by chrwm**
Closes #351 
Closes #349 

The PR 

- implements relevant ORM changes for correct data download with the API functions
- updates data documentation and metadata
- adds a section in the documentation for future wsdl changes
- adds print message of database path at database initialisation

### CODE REVIEW

**Comment by chrwm** [comment]
@deniztepe @FlorianK13 please also test if you can download with bulk and later update with API, to rule out inconsistencies between bulk and API data structures.
p.s.: For me, it worked but might be good to check it nevertheless.

**Comment by FlorianK13** [comment]
We should somehow tell the users if they still have the old sqlite database they run into the problem with the wrong column names (since the database will not be build newly according to the orm file).

**Comment by chrwm** [comment]
True, I think the new wiki section would be the place which is closest connected to the topic - or do you have another place in mind?

-> I added it to the documentation

**Review by deniztepe — APPROVED** [review]
Changes seem complete and all tests are succeeded also locally.

**Pull request merged**
