### PR TITLE
Delete content belonging to old paper

### LINKED ISSUE #552: Clean up `scripts` folder
- [x] Move code that is only used for the "Monitoring" paper to another repository

### PR DESCRIPTION
**Pull request by FlorianK13**
## Summary of the discussion

There are old code artefacts that we want to delete.

### PR-Assignee
- [x] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
- [x] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CHANGELOG.md)
- [ ] 📙 Update the documentation

### Reviewer
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

### CODE REVIEW

**Comment by FlorianK13** [comment]
@nesnoj are there additional things we want to delete? I think `scripts`, `tests`, and `postprocessing` contains code that is old and outdated.

This could also resolve #555 if we delete requirements.txt that are lying in these folders.

**Comment by nesnoj** [comment]
Let's get back to this in our JF

**Review by nesnoj — DISMISSED** [review]
Add link to the code backup (paper repo @FlorianK13 ) to changelog

**Comment by FlorianK13** [comment]
I added the link to the CHANGELOG, hence I think we can merge this. Do you agree @nesnoj ?

**Review by nesnoj — APPROVED** [review]
Yes, that's fine! Thx for cleaning up!

**Pull request merged**
