### PR TITLE
Bugfix 274 package import

### PR DESCRIPTION
**Pull request by FlorianK13**
With initial tests, the download factory class seems not to be needed. We have to test this further.

### CODE REVIEW

**Comment by FlorianK13** [comment]
@chrwm Can you check if you can still use parallel_processes on this branch to download entries via API?

**Comment by chrwm** [comment]
I'll check later today when their maintenance is done.
"Wir optimieren das MaStR-Webportal für Sie.
Daher steht das MaStR-Webportal heute von 07:30 Uhr bis ca. 09:30 Uhr nicht zur Verfügung."

**Comment by chrwm** [comment]
I get the following error:

```
`2022-07-14 12:35:36,982 [INFO] Backfill successfully finished
Downloading extended_unit_data (biomass):   0%|          | 0/10 [00:00<?, ?unit/s]
Traceback (most recent call last):
  File "/home/cwm/Python/open-mastr/main.py", line 80, in <module>
    db.download(
  File "/home/cwm/Python/open-mastr/open_mastr/mastr.py", line 187, in download
    mastr_mirror.retrieve_additional_data(
  File "/home/cwm/Python/open-mastr/open_mastr/soap_api/mirror.py", line 391, in retrieve_additional_data
    unit_data, missed_units = self.mastr_dl.additional_data(
  File "/home/cwm/Python/open-mastr/open_mastr/soap_api/download.py", line 811, in additional_data
    data, data_missed = self._retrieve_data_in_parallel_process(
  File "/home/cwm/Python/open-mastr/open_mastr/soap_api/download.py", line 875, in _retrieve_data_in_parallel_process
    data_tmp, data_missed_tmp = unit_result.next(timeout=timeout)
  File "/home/cwm/miniconda3/envs/open-MaStR/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/home/cwm/miniconda3/envs/open-MaStR/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/cwm/miniconda3/envs/open-MaStR/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/cwm/miniconda3/envs/open-MaStR/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'MaStRAPI._mastr_wrapper.<locals>.wrapper'`

```

From this [video ](https://www.youtube.com/watch?v=amuJHgegSn0)it says that python uses pickling internally when it sends objects between instances of python when using the multiprocessing module.

Pickling [documentation](https://docs.python.org/2/library/multiprocessing.html#pipes-and-queues)

I started [digging ](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function) a little deeper. The factory could have been the solution to make the worker processes pickleable. I would need to spend more time investigating and understanding further.

**Comment by FlorianK13** [comment]
Ok, I got the same error when I run the tests with multiprocessing. I will have a look if the package `pebble` mentioned in #239 can help us here.

**Comment by chrwm** [comment]
This branch is still in development and could be converted back to a draft pull request, isn't it?

**Comment by FlorianK13** [comment]
With the new bug report #313 I think we should pause the parallel download with the API for now and rather have a working import.

**Comment by FlorianK13** [comment]
I would suggest the following: 

- [x] Deactivate the parallel Download
- [x] Adapt the documentation (Parallel download does not work right now)

After that we could have a release 0.11.5

What do you think @chrwm ?

**Review by deniztepe — APPROVED** [review]

**Pull request merged**
